// async function 



// ------------------------------------------------------------------------
// function sub(a, b) {
//   try {
//     if (b > a) {
//       throw new Error("B cannot be greater than A!!");
//     }
//     const result = a - b;
//     console.log(result);
//   } catch (err) {
//     console.error("An Error Occured:", err.message);
//   }
// }
// sub(12, 15);
// ------------------------------------------------------------------------
// function sub(a, b) {
//   if (b > a) {
//     throw new Error("B cannot be greater than A!!");
//   }
//   return a - b;
// }
// try {
//   let result = sum(10, 20);
//   console.log(result);
// } catch(err) {
//   console.log("An Error Occured:", err.message);
// }